export const ROOT = '/'
export const FAVORITES = 'favorites'
export const HISTORY = 'history'
export const SEARCH = 'search'
export const FILM_PAGE = 'filmPage/:id'
export const GOTO_FILM_PAGE = '/filmPage/'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const NOT_FOUND = '*'

export const API_GET_FEATURE = '/api/feature-flags'
export const API_URL = 'http://localhost:3000'
export const APP_URL = 'http://localhost:5173'
