export const ROOT = '/'
export const FAVORITES = 'favorites'
export const HISTORY = 'history'
export const SEARCH = 'search'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const NOT_FOUND = '*'
